### ISSUE TITLE
newer cabal settings practices?

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesod-scaffold#105]
If you make the cabal version newer, it will bring this warning:

```
Warning: Packages using 'cabal-version: >= 1.10' must specify the
'default-language' field for each component (e.g. Haskell98 or Haskell2010).
If a component uses different languages in different modules then list the
other ones in the 'other-languages' field.
Warning: For packages using 'cabal-version: >= 1.10' the 'extensions' field is
deprecated. The new 'default-extensions' field lists extensions that are used
in all modules in the component, while the 'other-extensions' field lists
extensions that are used in some modules, e.g. via the {-# LANGUAGE #-}
pragma.
```

Surely nobody is using Cabal 1.8 still. Doesn't this mean that the scaffolding should be updated to have default-extensions vs other-extensions and to specify the language? And why would anyone use Haskell98 still anyway, shouldn't we all be using Haskell2010 by now?

**Comment by gregwebs** [comment]
Want to send a PR for this change?

**Comment by wolftune** [comment]
@gregwebs  I'd love to be confident enough to do so, but the reason for all my question marks is that I'm not certain about this stuff, so I need to defer to more experienced people. I also have the *idea* that `default-extensions` include stuff like `shakespeare` while `other-extensions` is stuff like `OverloadedStrings` but I really don't quite grasp all of this yet with confidence. Maybe I'll get there soonish…

**Comment by MaxGabriel** [comment]
I think this can be closed—if you generate a new project (e.g. `stack new test-cabal yesod-postgres`) and check the cabal file, there are `default-language` values specified and there is no `extensions` (or `default-extensions`) present.
