### ISSUE TITLE
When scaffolding new site we have _LOWER trail

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesod-scaffold#130]
![settings_yml_ __library_webserver_documents_haskell_yesod-scaffold-build](https://cloud.githubusercontent.com/assets/125707/18176514/943f1784-707e-11e6-9ea9-83ffbef7dee2.jpg)

Can you please point me to where the replacement happens so I can provide a PR, I didn't find it here /stack-templates/stack itself.

**Comment by snoyberg** [comment]
It appears here: https://github.com/yesodweb/yesod-scaffold/blob/master/Shared.hs#L47, thanks!

**Comment by MaxGabriel** [comment]
Closed by #163
