### ISSUE TITLE
(doc request) how to test Handler-ish things?

### ISSUE THREAD

**Issue by jwaldmann** [yesodweb/yesod-scaffold#143]
Hi. I can reproduce how to write and run trivial tests on the DB (like this snippet from the README)
```
withApp $ it "something" $ do
  users <- runDB $ selectList [] [] :: YesodExample App [Entity User]
  assertEq "length" 73 $ length users
```
This uses  `runDB` as given in the TestImport example.

I am not seeing how to test functions from my application that use the "real" runDB, and thus have type `HandlerT App IO a` (and I don't want to change their type).

**Comment by snoyberg** [comment]
Does this work for you?

```haskell
runHandler :: Handler a -> YesodExample App a
runHandler handler = do
    app <- getTestYesod
    fakeHandlerGetLogger appLogger app handler
```

I think we can just add it to the scaffolding.

**Comment by jwaldmann** [comment]
thanks! works.

**Comment by psibi** [comment]
@jwaldmann Thanks, closing the issue. If you have time, consider contributing this to the cookbook: https://github.com/yesodweb/yesod-cookbook
