### ISSUE TITLE
Add a default=NULL to each Text Maybe column

### ISSUE THREAD

**Issue by vitalijzad** [yesodweb/yesod-scaffold#144]
Could you please add a `default=NULL` to each `Text Maybe` column?

For example:

```
User
    ident Text
    password Text Maybe default=NULL
    UniqueUser ident
    deriving Typeable
```

That would be a workaround of [this persistent issue](https://github.com/yesodweb/persistent/issues/563).

**Comment by snoyberg** [comment]
It looks like this just affects MySQL, right? Could you send a PR for that branch of this repo?
