### ISSUE TITLE
Need for per file language pragmas

### ISSUE THREAD

**Issue by amitaibu** [yesodweb/yesod-scaffold#152]
As I copy some code form other old scaffolded projects to the new one, I seem the stumble upon more "errors" that require finding and adding the correct language pragmas.

It took me a few minutes to understand why I got parse errors for:
```haskell
 [whamlet|
   <p>
        Form is out-dated. Re-submit it.
|]
```
(because the handler file is missing `{-# LANGUAGE QuasiQuotes #-}`)

I wonder if we can't re-add those global pragmas we had in the manual cabal file back?

**Comment by snoyberg** [comment]
See the discussion at: https://github.com/yesodweb/yesod-scaffold/pull/147

**Comment by amitaibu** [comment]
Yeah, I saw it. My take was that it adds yet another barrier for beginners to write their handler.  Closing for now.
