### ISSUE TITLE
DevelMain should use forkFinally

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/yesod-scaffold#182]
@k0001 says [in a PR review](https://github.com/parsonsmatt/servant-persistent/pull/33#pullrequestreview-121812430):

> You probably want to use `forkFinally`. Check the _`mask` and `forkIO`_ section here: https://www.safaribooksonline.com/library/view/parallel-and-concurrent/9781449335939/ch09.html

**Comment by snoyberg** [comment]
Good catch, thanks! I've opened #183 to fix this and update the docs.

**Comment by arrowd** [comment]
This can be closed, I guess?

**Comment by psibi** [comment]
Yeah. Thanks for reminding!
