### ISSUE TITLE
Add an example of a static resources in template to scaffolding

### ISSUE THREAD

**Issue by hyperpape** [yesodweb/yesod-scaffold#184]
If the initial templates included in the scaffolding are intended to be examples to help newcomers, I think it would be helpful to show an example of a static resource (perhaps an image) in a hamlet file. I recently didn't quite understand the syntax rules, and had to ask around for help.

**Comment by psibi** [comment]
@hyperpape IMO, there are lots of things newcomers may get stuck by. A better place IMO is to put them under the cookbook: https://github.com/yesodweb/yesod-cookbook

I would be glad to accept a PR showcasing the above example.

**Comment by hyperpape** [comment]
That seems reasonable. I'll look at the cookbook--I wasn't really aware of it as a resource.
