### ISSUE TITLE
Environment variable names

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/yesod-scaffold#185]
Right now, the environment variables in `config/settings.yml` are unprefixed, e.g. `HOST`, `PORT`, and `STATIC_DIR`. This has caused issues in at least one place, see https://github.com/yesodweb/yesod/issues/1517. Should we prefix all of the variables with, e.g. `YESOD_`? Should we only prefix variables that are likely to be overloaded, like `HOST` and `PORT`?

CC @rszibele @psibi @StevenXL @bitemyapp

**Comment by psibi** [comment]
I don't have a strong opinion either way. But I would prefer everything to be prefixed.

**Comment by rszibele** [comment]
I would personally prefix all environment variables. This would have two advantages in comparison to only prefixing variables that are likely to be overloaded:

1. Ensuring similar occurrences will not happen with other variables.
2. Providing a consistent naming convention of environment variables. Having some variables prefixed and others not could be confusing to newcomers.

**Comment by snoyberg** [comment]
Looks like pretty universal support for prefixing all the variables, I'll make the update.

**Comment by snoyberg** [comment]
Alright, changes pushed, closing.
