### ISSUE TITLE
Currently yesod scaffolding is broken on windows. 

### ISSUE THREAD

**Issue by hanjoosten** [yesodweb/yesod-scaffold#204]
I am trying to build yesod from scratch, using stack. I have a windows machine. 

The first attempt was simple:

```
stack new yesodwebSimple yesodweb/simple
stack build
```
I expected it to build, but it failed. 

There are [several issues with windows / ghc 8.8](https://gitlab.haskell.org/ghc/ghc/-/issues/17926#note_265527). So I thought to try ghc 8.10. There isn't an LTS yet for 8.10, so I tried to use  nightly-2020-09-19
I had to modify stack.yaml:

```
resolver: nightly-2020-09-19

extra-deps:
- classy-prelude-yesod-1.5.0
```

Now this failed too, with a strange error:

~~~
zlib                > configure
zlib                > Configuring zlib-0.6.2.2...
zlib                > build
zlib                > Preprocessing library for zlib-0.6.2.2..
zlib                > Building library for zlib-0.6.2.2..
zlib                > [1 of 5] Compiling Codec.Compression.Zlib.Stream
zlib                > ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe

--  While building package zlib-0.6.2.2 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.2.0.0_ghc-8.10.2.exe --builddir=.stack-work\dist\a3a5fe88 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

~~~

I don't use GitLab, and there is no `C:/GitLabRunner` directory on my machine. Where does this come from?

**Comment by hanjoosten** [comment]
Related to https://github.com/haskell/zlib/issues/35

**Comment by snoyberg** [comment]
This looks like a GHC bug to me

**Comment by Truedrog** [comment]
Try to use 8.8.4

**Comment by hanjoosten** [comment]
Wierd. I thought that I tried that one as well, but cannot reproduce this bug. Confusing, but it works for now.
