### ISSUE TITLE
Separating development-only packages from the package db needed for production

### ISSUE THREAD

**Issue by rehno-lindeque** [yesodweb/yesod-scaffold#30]
`DevelMain.hs` currently has these instructions for including `foreign-store` in your `.cabal` file
```haskell
-- You will need to add these packages to your .cabal file
-- * foreign-store >= 0.1 (very light-weight)
-- * warp (you already depend on this, it just isn't in your .cabal file)
```
Even though it's easy to add `foreign-store` by itself I've actually found that I also want to include several other tools in our REPL, none of which should get deployed to production.

So, I went about avoiding the above instructions using this workaround:
```sh
# Create a sandbox for development tools in devel/
# P.S. it would be cool if `yesod devel` started inside of ghci by default
mkdir devel ; cd devel/ ; cabal sandbox init ; cabal install foreign-store; cd ..

# Include the devel/ sandbox in ghci
cabal repl --ghc-options="-O0 -fobject-code -package-db ./devel/.cabal-sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d/"
```

```haskell
-- Unhide foreign-store and warp
λ :set -package warp
λ :set -package foreign-store

-- Load DevelMain
λ :l app/DevelMain.hs
λ DevelMain.update
```

I wonder if it would be worth adding something like this to the scaffold, would you be open to accepting a PR to this effect?

**Comment by creichert** [comment]
I agree here. #44 Seems to remove the instructions for installing `foreign-store` but adds the app/ directory to the library by default.

I'm in favor of only installing the DevelMain dependencies with the `-fdev` flag.

**Comment by gregwebs** [comment]
Just for foreign-store (a very small amount of code that depends on base) it is not worth the user confusion of having the dependency behind a flag. But if we want to add more it makes sense (groom is one I have used for pretty-printing) and we can re-open this.
