### ISSUE TITLE
Expose the config for other programs

### ISSUE THREAD

**Issue by erikd** [yesodweb/yesod-scaffold#33]
I am now working on my third yesod based web app where the data is loaded into the database from a Haskell program separate the web app itself. In this scenario, if I stick to the principles of DRY, the webapp and the datbase loading program need to read the same configuration info from the same files.

The last time I did this, I hacked the `Settings.hs` file so that both the webapp and the database loader can read the required configuration. This entails:

* No longer reading the environment (eg Development/Testing/Staging/Production) from the command line (I used a separate config/environment.yml file, but and environment variable or other ideas could also work).
* Moving the `PersistConf` field from the `App` structure to the `Extra` structure so it is bundled with the rest of the configuration.
* Exposing a `readConfig` function from `Settings.hs`.

I want to do this in the scaffoled because a) I'm sure I'm not the only one to ever want to do this and b) hacking it this way every time is a pain in the neck.

Comments?

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
