### ISSUE TITLE
Inconsistent indentation in Hamlet files

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod-scaffold#50]
[homepage.hamlet](https://github.com/yesodweb/yesod-scaffold/blob/7bff431e16949b568fadbd2b9abd88952da2e4f1/templates/homepage.hamlet) uses 2 space indentation, whereas [default-layout-wrapper.hamlet](https://github.com/yesodweb/yesod-scaffold/blob/7bff431e16949b568fadbd2b9abd88952da2e4f1/templates/default-layout-wrapper.hamlet) and [default-layout.hamlet](https://github.com/yesodweb/yesod-scaffold/blob/postgres/templates/default-layout.hamlet) use 4 space indentation. 

It seems inconsistent to use different spacing in the same scaffolded project, and makes it harder for a beginner to know which convention to prefer.

**Comment by gregwebs** [comment]
Consistency is good. I like 2 spaces for hamlet because unlike Haskell code you can't necessarily restructure it to avoid indentation.

**Comment by snoyberg** [comment]
I agree with consistency as well. I typically use 4 spaces everywhere, but I don't have a strong feeling on the matter, so I'm happy to go with @gregwebs suggestion.

@MaxGabriel interested in sending a pull request?

**Comment by MaxGabriel** [comment]
I like 2 spaces as well; I'll make a PR for it.

Unless you guys want to go with a 3 space compromise? ;)
