### ISSUE TITLE
Feature proposal: wipe database between tests in scaffolding

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod-scaffold#52]
I was talking with @bitemyapp and we both thought that'd it be nice if the scaffolding came with code to wipe the database between tests. Imo, that behavior is pretty foundational to a test suite.

I don't think its _super_ complicated to write such behavior; this is an [implementation for SQLite](https://gist.github.com/MaxGabriel/b9de84e85b5c697589b7). All of the SQL databases have different queries for getting the list of tables/truncating those tables, but they're similar in structure. MongoDB and Redis are easier to wipe.

Anyway, I'm interested in developing this but didn't know if you felt it fit a) in the scaffolding or b) as an external package included by the scaffolding or c) as an external package not included by the scaffolding.

**Comment by bitemyapp** [comment]
@MaxGabriel A lot of the problem, at least for me, was just getting an explicit `main.hs` that worked for the test runner.

**Comment by gregwebs** [comment]
In the scaffolding is good. I have code for this that I should find this weekend.

**Comment by bitemyapp** [comment]
@gregwebs having an explicit test runner is all I really wanted for the default scaffolding. Test database state reset would be icing on the cake.

**Comment by MaxGabriel** [comment]
Closing this because database wiping is implemented in all the backends.

**Comment by snoyberg** [comment]
And thank you for that :)
