### ISSUE TITLE
Scaffolding links to deprecated Chrome Frame for IE

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod-scaffold#60]
The [current scaffolding links to Chrome Frame](https://github.com/yesodweb/yesod-scaffold/blob/2dbf126b8a9ce1592fc861e9997db9c74b3a243f/templates/default-layout-wrapper.hamlet#L43) to support old IE versions, but based on the [linked page](chromium.org/developers/how-tos/chrome-frame-getting-started), Chrome Frame hasn't been supported since February, 2014. 

Probably that bit of the scaffolding should just be removed?

IE 6 Usage: https://www.modern.ie/en-us/ie6countdown

**Comment by snoyberg** [comment]
Agreed, that's a good call. Would you be able to send a PR?

Speaking of PRs...

**Comment by MaxGabriel** [comment]
Yeah
