### ISSUE TITLE
minimal should depend on yesod-core and import Yesod.Core

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod-scaffold#65]
I love the minimal branch for getting folks up and running with a small, understandable scaffold. Unfortunately compiling all of the yesod package is time consuming. Only yesod-core is needed to run this scaffold. All that's needed is to update build-depends to yesod-core and `import Yesod.Core` instead in all the hs files.

**Comment by gregwebs** [comment]
Now that we no longer recommend yesod-platform there is a lot of benefit to this. Want to send a pull request for it?

**Comment by pbrisbin** [comment]
I have one ready but I'm getting permission denied pushing my branch to this repo. I don't mind making my own fork, but being in the Org, I expected to be able to... any ideas?

**Comment by gregwebs** [comment]
Sorry, it still had default settings. You should be able to push now.

**Comment by pbrisbin** [comment]
Awesome thanks. PR opened.
