### ISSUE TITLE
Add DB alias

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/yesod-scaffold#69]
_This is a place-holder so I don't forget about this. If someone wants to go ahead and do it, great. If not, I plan to PR this soon_

Functions suitable to pass to `runDB` can use the following type alias:

``` hs
type DB a = forall (m :: * -> *).
    (MonadIO m, Functor m) => ReaderT SqlBackend m a
```

This promotes composition and testing.

``` hs
findAdmin :: UserId -> Handler (Maybe User)
findAdmin = runDB $ -- ...

getFooR = do
    muser <- findAdmin uid
```

This `findAdmin` can't be (easily) tested or composed into other `runDB` invocations.

``` hs
findAdmin :: UserId -> DB (Maybe User)
findAdmin = -- ...

getFooR = do
    muser <- runDB $ findAdmin uid
```

This `findAdmin` can be composed into other `runDB` calls and easily tested with `TestImport.runDB`.

**Comment by snoyberg** [comment]
@pbrisbin bump

**Comment by gregwebs** [comment]
I always add this

**Comment by pbrisbin** [comment]
Sorry I vanished on this. I changed jobs and got busy with non-Haskell work. I still think this is valuable but I won't have the time to implement and test for probably a few more weeks.
