### ISSUE TITLE
Add an example of using Yesod as an API server to the scaffolding

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod-scaffold#73]
Seems like it would be good for newcomers to have an example of returning JSON in the scaffolding, based on discussion in: https://github.com/yesodweb/yesod/pull/993

Presumably 1–2 additional handler function(s) would be added to the HomeHandler for this.

I don't think I can create new labels, but this issue could probably be tagged "newcomer".

**Comment by meteficha** [comment]
Just to be sure, my opinion is not that we should have JSON returning examples on the scaffold.

My opinion is that there should be another, separate scaffold for API servers.  It should be stripped of everything not relevant to them, be preconfigured with sane options and, of course, include JSON examples.

**Comment by gregwebs** [comment]
My opinion is that both should be done.

**Comment by snoyberg** [comment]
+1 from me

**Comment by MaxGabriel** [comment]
This is closed by #76
