### ISSUE TITLE
Update to yesod-static 1.5?

### ISSUE THREAD

**Issue by tdimiduk** [yesodweb/yesod-scaffold#78]
The scaffolding generated by yesod-bin 1.4.9.2 calls out yesod-static < 1.5, where the current version on hackage (and nixpkgs) is 1.5. Is there an update in the works? It looks like the repository here still has < 1.5, or am I reading things incorrectly?

**Comment by gregwebs** [comment]
as a data point, stackage nightly is on to 1.5, but LTS is still < 1.5

**Comment by tdimiduk** [comment]
Has anyone tested with yesod-static 1.5? When I relax the constraint I am getting a compile error of:

ghc: ghc no longer supports single-file package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format. 

It is quite possible that error is due to something else in my setup, but if someone with more wisdom could tell me if that could be due to a newer yesod-static, that would be useful.

**Comment by snoyberg** [comment]
Try running cabal clean and try again.
