### ISSUE TITLE
Magic AppSettings

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod-scaffold#84]
In the scaffolded `Settings.hs` file, there is an [interesting line](https://github.com/yesodweb/yesod-scaffold/blob/postgres/Settings.hs#L58) that starts off the `FromJSON` instance like this:

    parseJSON = withObject "AppSettings" $ \o -> do

I know what `withObject` does, so it seems weird that the maps and arrays in `config/settings.yaml` aren't all under one big `AppSettings` key. I suspect that in one of the packages used for these default setups, there is code that is merging the file with environment variables and for some reason needs to nest things under one top-level key. If someone could tell me where that is, I would be happy to put up a PR to document this a little better in the scaffold.

**Comment by snoyberg** [comment]
That's not the way `withObject` works, the argument `AppSettings` is just to make for nicer error messages.

**Comment by andrewthad** [comment]
Dang, I feel dumb. Thanks.

**Comment by MaxGabriel** [comment]
I personally think the Aeson haddocks on `withObject` & co. are kind of confusing and could use an example. Mostly saying this as a reminder to myself, unless you were interested @andrewthad
