### ISSUE TITLE
Have Travis CI test the scaffolding

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/yesod-scaffold#95]
It'd be nice if the scaffolding was tested by Travis CI, that way we can tell if PRs to the scaffolding are safe to merge. This could also mean that scaffolded projects start with a `.travis.yml` file, which is nice.

The different branches might need different `.travis.yml` files (e.g. to start different databases).

**Comment by gregwebs** [comment]
doing this on the yesod-test-1.5 branch
